### PR TITLE
Fix Schema installer does not preserve answer input for dbHost or dbP…

### PR DESCRIPTION
**Pull request by aregier**
…ort #1

### CODE REVIEW

**Comment by aregier** [comment]
Fixes #1

**Comment by jsumners** [comment]
😣

Thank you for the fix. I don't know how I haven't seen this problem.

**Comment by aregier** [comment]
Quite welcome. Thanks for incorporating it so quickly :-)

**Comment by jsumners** [comment]
v0.3.0 has been published to npm

**Comment by jsumners** [comment]
@aregier since you have submitted this PR, I am fairly certain you will be interested in https://github.com/jscas/cas-server/pull/6 .

**Pull request merged**
